---
title: "eda_plots"
author: "Hattie"
date: "6/10/2020"
output: pdf_document
---

```{r}
## Load libraries.
library(lubridate)
library(viridis)
library(ggplot2)
library(tidyr)
library(readr)
library(dplyr)
library(RColorBrewer)

## Load data.
load('../data/data.Rdata')

## Number of experiments = 8.
N <- 8
OUTPUT <- FALSE
```

```{r}
str(data)
head(data)
colnames(data)
view(data)
```

## TAKING OUT OUTLIERS 
```{r}
ex1 <- data %>% 
  filter(experiment == 1) 
trimmed_ex1 <- ex1[400:(nrow(ex1)-100), ]
trimmed_ex1 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()

ex2 <- data %>% 
  filter(experiment == 2) 
trimmed_ex2 <- ex2[500:(nrow(ex2)-90), ]
trimmed_ex2 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()

ex3 <- data %>% 
  filter(experiment == 3) 
trimmed_ex3 <- ex3[300:(nrow(ex3)-50), ]
trimmed_ex3 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()

ex4 <- data %>% 
  filter(experiment == 4) 
trimmed_ex4 <- ex4[500:(nrow(ex4)-60), ]
trimmed_ex4 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()

ex5 <- data %>% 
  filter(experiment == 5) 
trimmed_ex5 <- ex5[360:(nrow(ex5)-30), ]
trimmed_ex5 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()

ex6 <- data %>% 
  filter(experiment == 6) 
trimmed_ex6 <- ex6[400:(nrow(ex6)-290), ]
trimmed_ex6 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()

ex7 <- data %>% 
  filter(experiment == 7) 
trimmed_ex7 <- ex7[21:(nrow(ex7)), ]
trimmed_ex7 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()

ex8 <- data %>% 
  filter(experiment == 8) 
trimmed_ex8 <- ex8[36:(nrow(ex8)-22), ]
trimmed_ex8 %>% 
  ggplot(aes(time, feed_pressure_psi)) +
  geom_line()
```

```{r}
data %>%
  select(-time, -mode) %>%
  group_by(experiment) %>%
  summarise_all(mean) %>%
  as.data.frame


for (i in 1:N) {
  df <- gather(data, key = measure, value = value,
               c('perm_cond_high_us', 'perm_cond_low_us'))
  g <- df %>%
    filter(experiment == i) %>%
    ggplot(aes(time, value, group = measure, color = measure)) +
    geom_line() +
    ggtitle('Permeate Conductivity') +
    labs(subtitle = paste('Experiment', i), color = 'Measure') +
    xlab('Time') + ylab('Permeate Conductivity') + ylim(0, 1000) +
    scale_color_manual(values = c('SteelBlue', 'Orange3'),
                       labels = c('High', 'Low')) +
    theme_minimal()
  print(g)
}
rm(df, g)

## plots of feed pressure for each experiment.
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, feed_pressure_psi)) +
    geom_line(size = 0.25) +
    ggtitle('Feed Pressure') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Feed Pressure (psi)') + ylim(-5.61, 1114.9) +
    theme_minimal()
  print(g)
}

## plots of feed flowrate for each experiment.
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, feed_flow_lm)) +
    geom_line(size = 0.25) +
    ggtitle('Feed Flowrate') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Feed Flowrate') +
    theme_minimal()
  print(g)
}

## plots of water flux for each experiment.
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, water_flux_lmh)) +
    geom_line(size = 0.25) +
    ggtitle('Water Flux') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Water Flux (lmh)') +
    theme_minimal()
  print(g)
}


## water flux on time faceted by exp
data %>% 
  ggplot(aes(x = water_flux_lmh, y = time, color = factor(experiment))) + 
  geom_line() +
  facet_wrap(experiment~.)


## feed pump power ts
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, feed_pump_pow)) +
    geom_line(size = 0.25) +
    ggtitle('Feed Pump Power') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Feed Pump Power') +
    theme_minimal()
  print(g)
}

## permeate conductivity ts
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, perm_cond_high_us)) +
    geom_line(size = 0.25) +
    ggtitle('Perm (High) Conductivity') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Permeate Conductivity') +
    theme_minimal()
  print(g)
}

## permeate flow rate ts
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, permeate_flowrate_l_min)) +
    geom_line(size = 0.25) +
    ggtitle('Permeate Flow Rate') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Permeate Flow Rate') +
    theme_minimal()
  print(g)
}

## feed flow rate ts
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, feed_flow_lm)) +
    geom_line(size = 0.25) +
    ggtitle('Feed Flow Rate') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Feed Flow Rate') +
    theme_minimal()
  print(g)
}


## feed pressure ts
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(time, feed_pressure_psi)) +
    geom_line(size = 0.25) +
    ggtitle('Feed Flow Rate') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Feed Pressure') +
    theme_minimal()
  print(g)
}

## to see how conductivity changes as pump power increases
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(feed_pump_pow, perm_cond_high_us)) +
    geom_line() +
    ggtitle('Conductivity by Pump Power') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Pump Power') + ylab('Conductivity') +
    theme_minimal()
  print(g)
}


# lol this one was a fail but i will keep thinking on it
for (i in 1:N) {
  g <- data %>%
    filter(experiment == i) %>%
    ggplot(aes(mode, perm_flow_lm)) +
    geom_point(size = 0.25) +
    ggtitle('Water Flux') +
    labs(subtitle = paste('Experiment', i)) +
    xlab('Time') + ylab('Water Flux') +
    theme_minimal()
  print(g)
}

## ts perm cond plot
data %>%
  filter(experiment == 5) %>%
  ggplot(aes(time, perm_cond_high_us + perm_cond_low_us)) +
  geom_line() +
  scale_color_brewer(palette = "YlGnBu")
  



## feed pressure confidence intervals
feed_pressure_averages <- tapply(data$feed_pressure_psi, data$experiment, mean)
feed_pressure_sd <- tapply(data$feed_pressure_psi, data$experiment, sd)
feed_pressure_ss <- tapply(data$feed_pressure_psi, data$experiment, function(x) length(x))
feed_pressure_error <- qt(.975, df = feed_pressure_ss - 1) * feed_pressure_sd / sqrt(feed_pressure_ss)
feed_pressure_left <- feed_pressure_averages - feed_pressure_error
feed_pressure_right <- feed_pressure_averages + feed_pressure_error

## permeate conductivity (low) confidence intervals
perm_cond_averages <- tapply(data$perm_cond_low_us, data$experiment, mean)
perm_cond_sd <- tapply(data$perm_cond_low_us, data$experiment, sd)
perm_cond_ss <- tapply(data$perm_cond_low_us, data$experiment, function(x) length(x))
perm_cond_error <- qt(.975, df = perm_cond_ss - 1) * perm_cond_sd / sqrt(perm_cond_ss)
perm_cond_left <- perm_cond_averages - perm_cond_error
perm_cond_right <- perm_cond_averages + perm_cond_error

## water permeability coef confidence intervals
wp_averages <- tapply(data$water_perm_coef, data$experiment, mean)
wp_sd <- tapply(data$water_perm_coef, data$experiment, sd)
wp_ss <- tapply(data$water_perm_coef, data$experiment, function(x) length(x))
wp_error <- qt(.975, df = wp_ss - 1) * wp_sd / sqrt(wp_ss)
wp_left <- wp_averages - wp_error
wp_right <- wp_averages + wp_error


## experiment boxplots
  data %>% 
  ggplot(aes(experiment, water_perm_coef)) +
    geom_boxplot() +
    theme_minimal() +
    labs(title = "Water Permeability Coefficients",
       y = "Water Perm Coef",
       x = "Experiment") +
    scale_x_discrete(labels = c("1" = "10A",
                                "2" = "10B", 
                                "3" = "10C", 
                                "4" = "11A",
                                "5" = "11B",
                                "6" = "11C",
                                "7" = "12A",
                                "8" = "13")) +
    geom_segment(aes(x = .5, 
                     y = wp_left[1], 
                     xend = 1.5, 
                     yend = wp_left[1], 
                     color = "10A",
                     alpha = .5)) +
    geom_segment(aes(x = .5, 
                     y = wp_right[1], 
                     xend = 1.5, 
                     yend = wp_right[1], 
                     color = "10A",
                     alpha = .5)) +
    geom_segment(aes(x = 1.5, 
                     y = wp_left[2], 
                     xend = 2.5, 
                     yend = wp_left[2], 
                     color = "10B",
                     alpha = .5)) +
    geom_segment(aes(x = 1.5, 
                     y = wp_right[2], 
                     xend = 2.5, 
                     yend = wp_right[2], 
                     color = "10B",
                     alpha = .5)) +
    geom_segment(aes(x = 2.5, 
                     y = wp_left[3], 
                     xend = 3.5, 
                     yend = wp_left[3], 
                     color = "10C",
                     alpha = .5)) +
    geom_segment(aes(x = 2.5, 
                     y = wp_right[3], 
                     xend = 3.5, 
                     yend = wp_right[3], 
                     color = "10C",
                     alpha = .5)) +
    geom_segment(aes(x = 3.5, 
                     y = wp_left[4], 
                     xend = 4.5, 
                     yend = wp_left[4], 
                     color = "11A",
                     alpha = .5)) +
    geom_segment(aes(x = 3.5, 
                     y = wp_right[4], 
                     xend = 4.5, 
                     yend = wp_right[4], 
                     color = "11A",
                     alpha = .5)) +
    geom_segment(aes(x = 4.5, 
                     y = wp_left[5], 
                     xend = 5.5, 
                     yend = wp_left[5], 
                     color = "11B",
                     alpha = .5)) +
    geom_segment(aes(x = 4.5, 
                     y = wp_right[5], 
                     xend = 5.5, 
                     yend = wp_right[5], 
                     color = "11B",
                     alpha = .5)) +
    geom_segment(aes(x = 5.5, 
                     y = wp_left[6], 
                     xend = 6.5, 
                     yend = wp_left[6], 
                     color = "11C",
                     alpha = .5)) +
    geom_segment(aes(x = 5.5, 
                     y = wp_right[6], 
                     xend = 6.5, 
                     yend = wp_right[6], 
                     color = "11C",
                     alpha = .5)) +
    geom_segment(aes(x = 6.5, 
                     y = wp_left[7], 
                     xend = 7.5, 
                     yend = wp_left[7], 
                     color = "12A",
                     alpha = .5)) +
    geom_segment(aes(x = 6.5, 
                     y = wp_right[7], 
                     xend = 7.5, 
                     yend = wp_right[7], 
                     color = "12A",
                     alpha = .5)) +
    geom_segment(aes(x = 7.5, 
                     y = wp_left[8], 
                     xend = 8.5, 
                     yend = wp_left[8], 
                     color = "13",
                     alpha = .5)) +
    geom_segment(aes(x = 7.5, 
                     y = wp_right[8], 
                     xend = 8.5, 
                     yend = wp_right[8], 
                     color = "13",
                     alpha = .5))
    
    

  data %>% 
  ggplot(aes(experiment, perm_cond_low_us)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Permeate Conductivity",
       y = "Water Conductivity",
       x = "Experiment") +
  scale_x_discrete(labels = c("1" = "10A",
                              "2" = "10B", 
                              "3" = "10C", 
                              "4" = "11A",
                              "5" = "11B",
                              "6" = "11C",
                              "7" = "12A",
                              "8" = "13"))

  data %>% 
  ggplot(aes(experiment, feed_pressure_psi)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Feed Pressure",
       y = "Feed Pressure PSI",
       x = "Experiment") +
  scale_x_discrete(labels = c("1" = "10A",
                              "2" = "10B", 
                              "3" = "10C", 
                              "4" = "11A",
                              "5" = "11B",
                              "6" = "11C",
                              "7" = "12A",
                              "8" = "13"))
  
  
ns <- cumsum(tapply(data$experiment, data$experiment, length)[-8])
keep <- c(
  4908:84132,
  4238:81182 + ns[1],
  5323:80322 + ns[2],
  5585:84648 + ns[3],
  2991:75638 + ns[4],
  5558:90965 + ns[5],
  235:36045 + ns[6],
  624:79433 + ns[7]
)

data <- data %>%
  slice(keep)
  
exp.names <- c('10A', '10B', '10C', '11A', '11B', '11C', '12A', '13')
exp.salt <- c('35 g/L NaCl', '35 g/L NaCl', '35 g/L NaCl', 'Instant Ocean',
              'Instant Ocean', 'Instant Ocean', '1.5x Instant Ocean',
              'Instant Ocean')
exp.wave <- c('7.5 wave/min', '1.25 wave/min', '12 wave/min', '7.5 wave/min',
              '1.25 wave/min', '12 wave/min', '7.5 wave/min', 'NREL wave')
  ## Scatterplot matrices.
for (i in 1:N) {
  if (OUTPUT) {
    
    set.seed(1)
    data %>%
      filter(experiment == i) %>%
      slice(sample(1:nrow(.), 10000, replace = FALSE)) %>%
      select(water_flux_lmh, feed_pressure_psi, feed_pump_pow, feed_flow_lm,
             perm_flow_lm, rej_flow_lm, ac_current_a) %>%
      rename(
        flux = water_flux_lmh,
        feed_psi = feed_pressure_psi,
        feed_pow = feed_pump_pow,
        feed_flow = feed_flow_lm,
        perm_flow = perm_flow_lm,
        rej_flow = rej_flow_lm,
        ac_curr = ac_current_a
      ) %>%
      pairs(cex = 0.01, main = paste('Experiment', exp.names[i]))
    
    set.seed(1)
    data %>%
      filter(experiment == i) %>%
      slice(sample(1:nrow(.), 10000, replace = FALSE)) %>%
      select(water_perm_coef, feed_pressure_psi, feed_volume_l, feed_temp_c,
             perm_cond_low_us, rej_cond_ms) %>%
      rename(
        perm_coef = water_perm_coef,
        feed_psi = feed_pressure_psi,
        feed_vol = feed_volume_l,
        feed_temp = feed_temp_c,
        perm_cond = perm_cond_low_us,
        rej_cond = rej_cond_ms
      ) %>%
      pairs(cex = 0.01, main = paste('Experiment', exp.names[i])) 
  }
}

```

```{r}
## LASSO  !!!! yeehaw
test <- data %>% 
  filter(experiment == 1) %>% 
  select(-mode, -status, - ac_current_a, -rej_valve_open, -rej_flow_lm, -time, -experiment)

library(xts)
library(viridis)
library(glmnet)

predict.col <- which(colnames((test)) == "perm_cond_low_us")
yy <- as.matrix(test[,predict.col])
xx <- as.matrix(test[,-predict.col])

mod.ridge <- cv.glmnet(xx, yy, alpha=0)
coef(mod.ridge, s = mod.ridge$lambda.min)[ , 1]

weights <- 1/abs(matrix(coef(mod.ridge, s=mod.ridge$lambda.min)[, 1][-1]))^1

mod.adaptive <- cv.glmnet(xx, yy,  alpha = 1, penalty.factor = weights)

rain <- plasma(ncol(xx))
plot(mod.adaptive$glmnet.fit, xvar="lambda", label=TRUE, col=rain, cex.lab=1.5)
abline(v = log(mod.adaptive$lambda.min), col = "black")
abline(v = log(mod.adaptive$lambda.1se), col = "blue")
abline(v = log(6*mod.adaptive$lambda.1se),col= "red")
abline(v = 0,col="green")

s.list <- c(as.numeric(mod.adaptive$lambda.min), as.numeric(mod.adaptive$lambda.1se), as.numeric(6*mod.adaptive$lambda.1se), 1)

for(s in s.list) {
    coef <- coef(mod.adaptive, s=s)
    
    #Identify selected variables
    selected_attributes <- (coef@i[-1]) 
    colnames(xx)[selected_attributes]
    
    #Compute R-squared
    predictions <- predict(mod.adaptive, newx=xx, s=s)
    SSE=mean((yy-predictions)^2); print(SSE)
    SST=mean((yy-mean(yy))^2); print(SST)
    Rsqu=1-SSE/SST; print(Rsqu)
    
    #Plot prediction
    data1 <- yy
    data2 <- predictions
    max.val <- max(c(data1, data2))
    min.val <- min(c(data1, data2))
    data2plot <- cbind(data1, data2)
    
    plot(x = data2plot[,1], y = data2plot[,2]
         , xlim=c(min.val,max.val), ylim=c(min.val,max.val)
         , xlab="Actual", ylab="Predicted"
         , pch=20
         , main = paste("Lambda = ",round(s,3),", Variables = ", length(selected_attributes), collapse="")
         )
    abline(a=0,b=1,col="blue", lwd=2)
    
    legend("bottomright", 
           inset = c(-.01,-.01),
           legend = c("Observation", "Perfect Fit"
                      , paste0("R-sq = ",round(Rsqu,2))),
           col = c("black", "blue", NA),
           pch = c(20,NA, NA),
           lwd = c(NA,2, NA),
           bty = "n",
           cex=2)
}

par(mfrow=c(1,1))
plot(index(test), as.numeric(test$perm_cond_low_us), type="l", xlab="", ylab="")
lines(index(test),  predict(mod.adaptive, newx = xx, s=mod.adaptive$lambda.1se), col=2)
```



